/* Paths are relative to each game page under games/<name>/. */
const CATEGORIES = {
  animals: {
    id: "animals",
    name: "Animals",
    icon: "../../assets/animals/lion.png",
    items: [
      { id: "lion", name: "Lion", image: "../../assets/animals/lion.png" },
      { id: "elephant", name: "Elephant", image: "../../assets/animals/elephant.png" },
      { id: "giraffe", name: "Giraffe", image: "../../assets/animals/giraffe.png" },
      { id: "zebra", name: "Zebra", image: "../../assets/animals/zebra.png" },
      { id: "tiger", name: "Tiger", image: "../../assets/animals/tiger.png" },
      { id: "bear", name: "Bear", image: "../../assets/animals/bear.png" },
      { id: "penguin", name: "Penguin", image: "../../assets/animals/penguin.png" },
      { id: "frog", name: "Frog", image: "../../assets/animals/frog.png" },
      { id: "rabbit", name: "Rabbit", image: "../../assets/animals/rabbit.png" },
      { id: "monkey", name: "Monkey", image: "../../assets/animals/monkey.png" },
      { id: "fox", name: "Fox", image: "../../assets/animals/fox.png" },
      { id: "deer", name: "Deer", image: "../../assets/animals/deer.png" },
      { id: "dog", name: "Dog", image: "../../assets/animals/dog.png" },
      { id: "cat", name: "Cat", image: "../../assets/animals/cat.png" },
      { id: "cow", name: "Cow", image: "../../assets/animals/cow.png" },
      { id: "pig", name: "Pig", image: "../../assets/animals/pig.png" },
      { id: "sheep", name: "Sheep", image: "../../assets/animals/sheep.png" },
      { id: "goat", name: "Goat", image: "../../assets/animals/goat.png" },
      { id: "chicken", name: "Chicken", image: "../../assets/animals/chicken.png" },
      { id: "duck", name: "Duck", image: "../../assets/animals/duck.png" },
      { id: "owl", name: "Owl", image: "../../assets/animals/owl.png" },
      { id: "bird", name: "Bird", image: "../../assets/animals/bird.png" },
      { id: "turtle", name: "Turtle", image: "../../assets/animals/turtle.png" },
      { id: "dinosaur", name: "Dinosaur", image: "../../assets/animals/dinosaur.png" },
    ],
  },
  food: {
    id: "food",
    name: "Food",
    icon: "../../assets/food/apple.png",
    items: [
      { id: "apple", name: "Apple", image: "../../assets/food/apple.png" },
      { id: "banana", name: "Banana", image: "../../assets/food/banana.png" },
      { id: "strawberry", name: "Strawberry", image: "../../assets/food/strawberry.png" },
      { id: "orange", name: "Orange", image: "../../assets/food/orange.png" },
      { id: "watermelon", name: "Watermelon", image: "../../assets/food/watermelon.png" },
      { id: "grapes", name: "Grapes", image: "../../assets/food/grapes.png" },
      { id: "pizza", name: "Pizza", image: "../../assets/food/pizza.png" },
      { id: "hamburger", name: "Hamburger", image: "../../assets/food/hamburger.png" },
      { id: "hot-dog", name: "Hot Dog", image: "../../assets/food/hot-dog.png" },
      { id: "cupcake", name: "Cupcake", image: "../../assets/food/cupcake.png" },
      { id: "ice-cream", name: "Ice Cream", image: "../../assets/food/ice-cream.png" },
      { id: "cookie", name: "Cookie", image: "../../assets/food/cookie.png" },
      { id: "carrot", name: "Carrot", image: "../../assets/food/carrot.png" },
      { id: "broccoli", name: "Broccoli", image: "../../assets/food/broccoli.png" },
      { id: "tomato", name: "Tomato", image: "../../assets/food/tomato.png" },
      { id: "cheese", name: "Cheese", image: "../../assets/food/cheese.png" },
      { id: "egg", name: "Egg", image: "../../assets/food/egg.png" },
      { id: "bread", name: "Bread", image: "../../assets/food/bread.png" },
      { id: "milk", name: "Milk", image: "../../assets/food/milk.png" },
      { id: "yogurt", name: "Yogurt", image: "../../assets/food/yogurt.png" },
      { id: "cereal", name: "Cereal", image: "../../assets/food/cereal.png" },
      { id: "donut", name: "Donut", image: "../../assets/food/donut.png" },
      { id: "fries", name: "Fries", image: "../../assets/food/fries.png" },
      { id: "avocado", name: "Avocado", image: "../../assets/food/avocado.png" },
    ],
  },
};

function getCategoryList() {
  return Object.values(CATEGORIES);
}
